### ISSUE TITLE
Cant access to okhttp Client builder

### ISSUE THREAD

**Issue by kewldan** [zhkl0228/impersonator#3]
I wanna add gzip uncompress interceptor or use socks proxy. But i cant unless i have to fork library and change code directry. I think impersonator should have interface for developer to modify okhttp client builder. what do you think?

**Comment by zhkl0228** [comment]
public static OkHttpClientFactory create(ImpersonatorApi api, OkHttpClientBuilderFactory okHttpClientBuilderFactory) {
        return new DefaultHttpClientFactory(api, okHttpClientBuilderFactory);
    }

**Comment by kewldan** [comment]
Thanks for help! My issue is solved
